os: linux
dist: bionic
language: node_js
node_js:
  - "stable"
env:
  - NODE_ENV=production
install:
  - yarn install --prod=false
script:
  - yarn build
after_sucess:
  - touch dist/.nojekyll
  - touch dist/CNAME
  - echo "yevgenybulochnik.com" > dist/CNAME
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  local_dir: dist
  on:
    branch: master
