service: mailer
frameworkVersion: '2'

plugins:
  - serverless-offline
  - serverless-dotenv-plugin

provider:
  name: aws
  runtime: nodejs12.x
  region: ${env:REGION}
  stage: ${env:STAGE}
  environment:
    TO_EMAIL: ${env:TO_EMAIL}
    SOURCE: ${env:SOURCE}
    CORS_DOMAIN: ${env:CORS_DOMAIN}
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "ses:SendEmail"
      Resource:
        - "*"

functions:
  mailer:
    handler: handler.mailer
    events:
      - http:
          path: mailer
          method: post
          cors:
            origin: ${env:CORS_DOMAIN}

custom:
  serverless-offline:
    host: 0.0.0.0
    httpPort: 3001
